# Домашнее задание "Производная функции нескольких аргументов".

In [2]:
import numpy as np
from scipy.optimize import approx_fprime

In [14]:
def func(x, c0, c1):
    return c0 * x[0]**2 + c1*x[1]**2


x = np.ones(2)

c0, c1 = (1, 200)

eps = np.sqrt(np.finfo(float).eps)

approx_fprime(x, func, eps, c0, c1)


array([  2.        , 400.00000381])

### Уровень 0:

Посчитайте частные производные функций:


1) $f(x,y)=2x^2y^3 + 1/x + y^2x + 7$, а для этой функции также градиент в точке $(1,2)$

2) $f(x,y)=x^2y - sin(xy) + cos(x^2) + 6y$

In [137]:
import sympy
from sympy import *
x,y = symbols('x y')

###  Функция №1

In [26]:
print('Функция №1 = ')
expression = 2*x**2 * y**3 + x**(-1) + y**2 * x + 7
expression

Функция №1 = 


2*x**2*y**3 + x*y**2 + 7 + 1/x

In [23]:
expression_dif_x = diff(expression,x)
print('Частная производная функции №1 по х = ')
expression_dif_x


Частная производная функции №1 по х = 


4*x*y**3 + y**2 - 1/x**2

In [25]:
expression_dif_y = diff(expression,y)
print('Частная производная функции №1 по y = ')
expression_dif_y

Частная производная функции №1 по y = 


6*x**2*y**2 + 2*x*y

In [51]:
def function(x):
    return  2*x[0]**2 * x[1]**3 + x[0]**(-1) + x[1]**2 * x[0] + 7

In [52]:
print('Градиент в точке [1,2]')
approx_fprime([1,2], function, eps)

Градиент в точке [1,2]


array([35.00000024, 28.00000024])

###  Функция №2
$f(x,y)=x^2y - sin(xy) + cos(x^2) + 6y$

In [43]:
print('Функция №2 = ')
expression = x**2 * y - sin(x*y) + cos(x**2) + 6*y
expression

Функция №2 = 


x**2*y + 6*y - sin(x*y) + cos(x**2)

In [44]:
expression_dif_x = diff(expression,x)
print('Частная производная функции №1 по х = ')
expression_dif_x


Частная производная функции №1 по х = 


2*x*y - 2*x*sin(x**2) - y*cos(x*y)

In [45]:
expression_dif_y = diff(expression,y)
print('Частная производная функции №1 по y = ')
expression_dif_y

Частная производная функции №1 по y = 


x**2 - x*cos(x*y) + 6

In [47]:
def function(x):
    return  x[0]**2 * x[1] - sin(x[0]*x[1]) + cos(x[0]**2) + 6*x[1]

In [49]:
print('Градиент в точке [1,2]')
approx_fprime([1,2], function, eps)

Градиент в точке [1,2]


array([3.14935184, 7.41614687])

### Уровень 1:

Градиентный спуск своими руками:

In [55]:
from scipy.misc import derivative

In [118]:
np.set_printoptions(formatter={'float_kind': '{:.5f}'.format  })

In [53]:
def f(x):
    return (x[0]**2) + (x[1]**2)

In [120]:
x = np.array([100, 200])
learning_rate = 0.1
accuracy = 1e-6

print('gradient: \t|\t point coordinates:')
print('-'*55)
for i in range(100):
    # Calculate gradient
    grad = approx_fprime(x,f,eps)
    print(grad, end=' \t |\t')
    
    #grad = derivative(f,x,dx=1e-6,n=1)
    #print(f'{grad:.5f}', end=' \t |\t')
    
    # Update x with gradient
    x = x - learning_rate * grad
    print(x)
    
    #Stop criteria
    if grad.sum() <= accuracy: 
        print('-'*55)
        print(f'Total iterations = {i}') 
        break
        
print('-'*55)
print("Минимум достигается в: ", x)
print("Значение функции в минимуме: %.2f" % f(x))

gradient: 	|	 point coordinates:
-------------------------------------------------------
[200.00000 400.00000] 	 |	[80.00000 160.00000]
[160.00000 320.00000] 	 |	[64.00000 128.00000]
[128.00000 256.00000] 	 |	[51.20000 102.40000]
[102.40002 204.79993] 	 |	[40.96000 81.92001]
[81.92004 163.84009] 	 |	[32.76799 65.53600]
[65.53595 131.07202] 	 |	[26.21440 52.42880]
[52.42880 104.85757] 	 |	[20.97152 41.94304]
[41.94302 83.88608] 	 |	[16.77722 33.55443]
[33.55443 67.10886] 	 |	[13.42177 26.84355]
[26.84354 53.68709] 	 |	[10.73742 21.47484]
[21.47483 42.94967] 	 |	[8.58994 17.17987]
[17.17987 34.35974] 	 |	[6.87195 13.74390]
[13.74390 27.48779] 	 |	[5.49756 10.99512]
[10.99512 21.99023] 	 |	[4.39805 8.79609]
[8.79609 17.59219] 	 |	[3.51844 7.03687]
[7.03687 14.07375] 	 |	[2.81475 5.62950]
[5.62950 11.25900] 	 |	[2.25180 4.50360]
[4.50360 9.00720] 	 |	[1.80144 3.60288]
[3.60288 7.20576] 	 |	[1.44115 2.88230]
[2.88230 5.76461] 	 |	[1.15292 2.30584]
[2.30584 4.61169] 	 |	[0.92234 1.84467]
[1.

Проверка с помощью функции "minimize"

In [91]:
from scipy.optimize import minimize

In [93]:
res = minimize(f,x,method='nelder-mead', options={'xtol':1e-8, 'disp':True})

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 79
         Function evaluations: 150



Проверка с помощью встроенной функции numpy:

In [136]:
#make points grid
a = np.arange(-200,200,1)

In [140]:
#make functions output grid
expression = x**2 + y**2
fr = lambdify( [x,y] , expression , 'numpy' )
function_array = fr(a,a)

In [144]:
#make gradient grid
gradient_array = np.gradient(function_array)

In [149]:
# find position where gradient = 0
position = np.argwhere(gradient_array == 0 )

In [157]:
# find coorinates of this point point_coordinates = [coordinate,coordinate]
coordinate = -200 + position[0][0]*1

In [158]:
fr(coordinate,coordinate)

0

Функция имеет градиент = 0 в точке [0,0].  

Если градиент = 0, то это экстремум функции. Так как, такой градиент(равный 0) всего 1  - стало быть это глобальный максимум.   

Значение в глобальном максимуме = 0, глобальный максимум находится по координатам  [0,0].